---
- name: Debian Puppet package
  apt:
    deb: https://apt.puppetlabs.com/puppet5-release-xenial.deb
    update_cache: yes
  when: ansible_os_family == 'Debian'    

- name: Install Puppet Debian
  apt:
    name: puppet-agent
  when: ansible_os_family == 'Debian'

- name: CentOS Puppet package
  yum:
    name: https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
  when: ansible_os_family == 'RedHat'

- name: Install Puppet CentOS
  yum:
    name: puppet-agent
  when: ansible_os_family == 'RedHat'
